<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="0" skipped="3" tests="7" time="0.192" timestamp="2025-07-22T15:14:06.736074" hostname="DESKTOP"><testcase classname="test_failTests" name="test_funFailOne" time="0.001"><skipped type="pytest.xfail" message="What ever reason" /></testcase><testcase classname="test_failTests" name="test_funFailTwo" time="0.001"><skipped type="pytest.xfail" message="Known Bug here" /></testcase><testcase classname="test_failTests" name="test_funFailThree" time="0.001" /><testcase classname="test_failTests" name="test_funFailFour" time="0.002"><skipped type="pytest.xfail" message="Enforcing Failure" /></testcase><testcase classname="test_failTests" name="test_funModOne" time="0.003" /><testcase classname="test_failTests" name="test_funModTwo" time="0.001" /><testcase classname="test_failTests" name="test_funModThree" time="0.001" /></testsuite></testsuites>